project_id = "ztdzyzyvczjuwrnzepea"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = []

[auth.email]
enable_confirmations = false
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
